# Dataset for the Number Sequence Sorting (NSS) Task (w/ Bubble sort)

Given a sequence of numbers, the code here will generate the next step in the bubble sort for the given number sequence. The next step is the index of the number that needs to be swapped with the next number. 

For example, 
input: [0, 2, 1] -> output: [1]

If the number sequence is already sorted, then the output is [-1]


In [1]:
# dependency
# public
import os
import numpy as np
from tqdm import tqdm
# private
from utils import *

In [3]:
# helper functions for bubble sort 
def bubble_sort(seq): 
    n = len(seq) 
    for i in range(n): 
        for j in range(0, n-i-1):
            if seq[j] > seq[j+1]: 
                seq[j], seq[j+1] = seq[j+1], seq[j] 
    return seq

def find_next_step_in_bubble_sort(seq): 
    n = len(seq) 
    for j in range(0, n-1):
        if seq[j] > seq[j+1]:
            return j
    return -1

def bubble_sort_step(seq, j): 
    # perform one bubble sort step
    seq[j], seq[j+1] = seq[j+1], seq[j] 
    return seq

# ------------------------------------------
# test the bubble sort algo
# seq = np.random.randint(10, size=[10,])
seq = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
print(seq)
a = seq
# bubble_sort(a) 
print(a)

i = 0
j = 0
while True: 
    j = find_next_step_in_bubble_sort(seq)
    i += 1
    print(i, j)
    if j == -1: 
        break
    seq = bubble_sort_step(seq, j)
    print(seq)
    print()
    
print(seq)     

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
1 0
[9, 10, 8, 7, 6, 5, 4, 3, 2, 1]

2 1
[9, 8, 10, 7, 6, 5, 4, 3, 2, 1]

3 0
[8, 9, 10, 7, 6, 5, 4, 3, 2, 1]

4 2
[8, 9, 7, 10, 6, 5, 4, 3, 2, 1]

5 1
[8, 7, 9, 10, 6, 5, 4, 3, 2, 1]

6 0
[7, 8, 9, 10, 6, 5, 4, 3, 2, 1]

7 3
[7, 8, 9, 6, 10, 5, 4, 3, 2, 1]

8 2
[7, 8, 6, 9, 10, 5, 4, 3, 2, 1]

9 1
[7, 6, 8, 9, 10, 5, 4, 3, 2, 1]

10 0
[6, 7, 8, 9, 10, 5, 4, 3, 2, 1]

11 4
[6, 7, 8, 9, 5, 10, 4, 3, 2, 1]

12 3
[6, 7, 8, 5, 9, 10, 4, 3, 2, 1]

13 2
[6, 7, 5, 8, 9, 10, 4, 3, 2, 1]

14 1
[6, 5, 7, 8, 9, 10, 4, 3, 2, 1]

15 0
[5, 6, 7, 8, 9, 10, 4, 3, 2, 1]

16 5
[5, 6, 7, 8, 9, 4, 10, 3, 2, 1]

17 4
[5, 6, 7, 8, 4, 9, 10, 3, 2, 1]

18 3
[5, 6, 7, 4, 8, 9, 10, 3, 2, 1]

19 2
[5, 6, 4, 7, 8, 9, 10, 3, 2, 1]

20 1
[5, 4, 6, 7, 8, 9, 10, 3, 2, 1]

21 0
[4, 5, 6, 7, 8, 9, 10, 3, 2, 1]

22 6
[4, 5, 6, 7, 8, 9, 3, 10, 2, 1]

23 5
[4, 5, 6, 7, 8, 3, 9, 10, 2, 1]

24 4
[4, 5, 6, 7, 3, 8, 9, 10, 2, 1]

25 3
[4, 5, 6, 3, 7, 8, 9, 10, 2,

In [3]:
# class for data generation of the Number Sequence Sorting (NSS) problem 
class NumberSequenceSorting(): 
    def __init__(self, seq_len, data_size, num_size):
        super().__init__()
        self.seq_len = seq_len
        self.data_size = data_size
        self.num_size = num_size 
        
    def find_next_step_in_bubble_sort(self, seq): 
        n = len(seq) 
        for j in range(0, n-1):
            if seq[j] > seq[j+1]:
                return j
        return -1
    
    def bubble_sort_step(self, seq, j): 
        # perform one bubble sort step
        seq[j], seq[j+1] = seq[j+1], seq[j] 
        return seq
    
    def convert_to_str(self, seq:list) -> str:
        seq = [str(number) for number in seq]
        return ' '.join(seq) 
    
    def generate_end2end(self):
        # generate random number sequence sa sample
        # with its sorted result as label
        xs, ys = [], []
        # to filter out duplicates
        num_seq_set = set()
        for i in tqdm(range(self.data_size)):
            while True:
                # get a random number sequence
                x = np.random.randint(self.num_size, size=[self.seq_len])
                # check duplicates
                if str(x) in num_seq_set:
                    continue
                else:
                    num_seq_set.add(str(x))
                    y = np.sort(x)
                    # convert a list of int to string
                    x = self.convert_to_str(x)
                    y = self.convert_to_str(y)
                    # append to dataset
                    xs.append(x)
                    ys.append(y)
                    break
                    
        return xs, ys
                
    def generate_recursive(self): 
        xs, ys = [], []
        # generate random number sequences
        x = np.random.randint(self.num_size, size=[self.data_size, self.seq_len])
        xs.append(x)
        y = [find_next_step_in_bubble_sort(s) for s in x]
        ys = y.copy()

        while not all(np.equal(y, -1)):
            for i in range(x.shape[0]):
                if y[i] != -1:
                    x[i] = bubble_sort_step(x[i], y[i])
                    y[i] = find_next_step_in_bubble_sort(x[i])
                    xs.append(x[i])
                    ys.append(y[i])

        xs = np.vstack(xs)
        ys = np.array(ys)

        # randomly select indices
        indices = np.random.choice(xs.shape[0], data_size, replace=False)
        xs = xs[indices]
        ys = ys[indices]

        return xs, ys

## Data Generation

In [4]:
# data parameters 
seq_len = 5
data_size = 10000
num_size = 10  # only allow number 0 -9 when setting to 10

In [5]:
generator = NumberSequenceSorting(seq_len, data_size, num_size)
# generator.generate_recursive()
xs, ys = generator.generate_end2end()

100%|██████████| 10000/10000 [00:01<00:00, 7602.04it/s]


In [6]:
len(xs)

10000

In [7]:
xs[:10]

['6 4 2 6 1',
 '9 5 3 0 8',
 '5 6 4 0 5',
 '2 6 0 2 3',
 '1 2 4 9 6',
 '2 4 3 7 2',
 '5 0 6 3 5',
 '6 6 5 5 6',
 '7 7 1 4 4',
 '2 9 9 5 0']

In [8]:
len(ys)

10000

In [9]:
ys[:10]

['1 2 4 6 6',
 '0 3 5 8 9',
 '0 4 5 5 6',
 '0 2 2 3 6',
 '1 2 4 6 9',
 '2 2 3 4 7',
 '0 3 5 5 6',
 '5 5 6 6 6',
 '1 4 4 7 7',
 '0 2 5 9 9']

In [10]:
# train val test split
dataset = np.array([(x, y) for x, y in zip(xs, ys)])
data_size = dataset.shape[0]
indices = np.random.permutation(data_size)
train_size = int(0.7*data_size)
val_size = int(0.15*data_size)
test_size = data_size - train_size - val_size
train_idxes = indices[:train_size]
val_idxes = indices[train_size: train_size+val_size]
test_idxes = indices[train_size+val_size:]
trainset = dataset[train_idxes]
valset = dataset[val_idxes]
testset = dataset[test_idxes]
print('train size', train_size, trainset.shape)
print('val size', val_size, valset.shape)
print('test size', test_size, testset.shape)

train size 7000 (7000, 2)
val size 1500 (1500, 2)
test size 1500 (1500, 2)


In [11]:
# to save dataset
outdir = 'nss/'
outdir = os.path.join(
    outdir, 
    'num_size_{}'.format(num_size), 
    'seq_len_{}'.format(seq_len), 
    'data_size_{}'.format(data_size))
if not os.path.exists(outdir): 
    os.makedirs(outdir)
outdir

'nss/num_size_10/seq_len_5/data_size_10000'

In [12]:
save_txt(os.path.join(outdir, 'train_x.txt'), trainset[:, 0])
save_txt(os.path.join(outdir, 'train_y.txt'), trainset[:, 1])
save_txt(os.path.join(outdir, 'val_x.txt'), valset[:, 0])
save_txt(os.path.join(outdir, 'val_y.txt'), valset[:, 1])
save_txt(os.path.join(outdir, 'test_x.txt'), testset[:, 0])
save_txt(os.path.join(outdir, 'test_y.txt'), testset[:, 1])

In [117]:
y = [['<pad>'], ['-1']]
y += [['1']] * 9
y = np.array(y)
y

array([['<pad>'],
       ['-1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1']], dtype='<U5')

In [118]:
def is_int(v):
    try:
        int(v)
        return True
    except:
        return False

In [127]:
is_numeric = np.vectorize(is_int, otypes=[bool])

In [134]:
np.where((is_numeric(y)) & (y!='-1'))[0]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
np.where(y!='-1')[0]

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
np.array(y)

array([['<pad>'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1']], dtype='<U5')

In [95]:
np.full(np.array(y).shape, 'completion').astype(str)

array([['completion'],
       ['completion'],
       ['completion'],
       ['completion'],
       ['completion'],
       ['completion'],
       ['completion'],
       ['completion'],
       ['completion'],
       ['completion']], dtype='<U10')

In [94]:
np.array_equal(np.array(y), np.full(np.array(y).shape, 1).astype(str))

True

In [79]:
np.full(np.array(y).shape, '-1')

array([['-1'],
       ['-1'],
       ['-1'],
       ['-1'],
       ['-1'],
       ['-1'],
       ['-1'],
       ['-1'],
       ['-1'],
       ['-1'],
       ['-1']], dtype='<U2')

In [61]:
import numpy as np

x = np.arange(10).reshape(1, 10)
x = np.repeat(x, 11, axis=0)
x = x.astype(str)
print(x.shape)
x

(11, 10)


array([['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']], dtype='<U21')

In [62]:
y = [-1]
y += [i for i in range(-1, x.shape[1]-1)]
y = np.array(y).reshape(x.shape[0], 1)
y

array([[-1],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8]])

In [63]:
swap_idxes = np.arange(x.shape[0])[np.where(y!=-1)[0]]
swap_idxes

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
x[swap_idxes, y[swap_idxes].T], x[swap_idxes, y[swap_idxes].T+1] = \
x[swap_idxes, y[swap_idxes].T+1], x[swap_idxes, y[swap_idxes].T]

In [65]:
x

array([['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['1', '0', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '2', '1', '3', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '3', '2', '4', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '4', '3', '5', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '5', '4', '6', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '6', '5', '7', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '7', '6', '8', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '8', '7', '9'],
       ['0', '1', '2', '3', '4', '5', '6', '7', '9', '8']], dtype='<U21')

In [46]:
y[swap_idxes].T

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
x[np.arange(len(x)), y.T].T

array([['9'],
       ['0'],
       ['1'],
       ['2'],
       ['3'],
       ['4'],
       ['5'],
       ['6'],
       ['7'],
       ['8'],
       ['9']], dtype='<U21')

In [60]:
np.where(y.isdigit())

AttributeError: 'numpy.ndarray' object has no attribute 'isdigit'

In [54]:
x[:, idx]

IndexError: arrays used as indices must be of integer (or boolean) type

In [ ]:
321 -> 123
bubble sort:
    0 -> 231
    1 -> 213
    0 -> 123

a better sort?:
    0 1 -> 123

In [ ]:
4321 -> 1234
bubble sort:
    0 -> 3421
    1 -> 3241
    0 -> 2341
    2 -> 2314
    1 -> 2134
    0 -> 1234
    
a better sort?:
    

In [73]:
np.random.randint(0, 9, (5))

array([0, 4, 0, 2, 5])

In [ ]:
0 0 4 2 5
0 0 2 4 5

In [76]:
import torch
# torch.nn.utils.rnn.pack_padded_sequence()
# torch.nn.utils.rnn.pack_sequence()

In [77]:
np.array(['<pad>']).astype(int)

ValueError: invalid literal for int() with base 10: '<pad>'